Amber-MD/pytraj

- note-books/parallel/rmsd_mpi.ipynb
- note-books/parallel/rmsd_mpi_example.py
Link for notebook:
http://nbviewer.ipython.org/github/pytraj/pytraj/blob/master/note-books/parallel/rmsd_mpi.ipynb
> PYTRAJ notebook: fix typos for mpi example + add comment about segfault

- note-books/speed_test_2_trajs.ipynb
1000 frames, >17K atoms,
(traj[0:1000:5])
FrameArray
1 loops, best of 3: 315 ms per loop
api.Trajectory <<-- superfast. numpy is rock.
The slowest run took 4.41 times longer than the fastest. This could mean that an intermediate result is being cached
100000 loops, best of 3: 17.9 µs per loop <<--- 20K times faster than FrameArray, 10K times faster than mdtraj
TrajReadOnly
1 loops, best of 3: 486 ms per loop
mdtraj
10 loops, best of 3: 189 ms per loop
> PYTRAJ: speed test for slicing: 10000 times faster

- pytraj/Frame.cpp
- pytraj/Frame.pyx
at least I can make the distance calculation for a single frame
as fast as mdtraj.
> PYTRAJ: pre-allocate python array instead of using 'append'

- note-books/energy_decomposition.ipynb
- pytraj/externals/get_pysander_energies.py
with sander.setup(parm, ...), `ParmEd` try to save to file and let
`sander` reload. In original verion in pytraj, we load from file to
AmberParm object. I made change by letting `sander` directly load from
file.
anyway, the interface does not change.
pyca.energy_decomposition(traj, parm=None)
parm: is optional, could be a filename, a AmberParm object from
`chemistry`. If `parm` is None, `pytraj` will look at `traj.top.filename`
> PYTRAJ: avoid load/reload/reload AmberParm

- pytraj/DataSetList.cpp
- pytraj/DataSetList.pyx
- tests/test_segfault.py
why? make this object live longer to avoid segmentation fault when
calling `traj.search_hhonds().groupby("SER")`
Before: need to do this
dslist = traj.search_hhonds()
d0 = dslist.groupby("SER")
> pytraj: increase reference for DataSetList when using groupby

- .travis.yml
Roughly cuts build times in half in my experience and builds start in seconds,
with more CPUs and memory to run tests with.
> Switch to the container infrastructure

- installs/install_cpptraj_current_folder.sh
- setup.py
This is how pytraj's setup currently work.
+ First, it will check if there is $CPPTRAJHOME env. If not, it will check if there is ./cpptraj in current folder
+ Then it will check if there is ``libcpptraj.so`` in $CPPTRAJHOME/lib or ./cpptraj/lib. If existing ./cpptraj/, pytraj will try to reinstall ``libcpptraj``.
This PR enhance this #800
> update setup.py when having ./cpptraj folder but does not have libcpptraj

- pytraj/__init__.py
- pytraj/core/cpptraj_core.pyx
- pytraj/datafiles/datafiles.pyx
- tests/test_load_state.py
something like
```python
traj = pt.iterload('data/tz2.nc', './data/tz2.parm7', frame_slice=frame_slice)
text = '''
rms @CA
radgyr @CA nomax
'''
s = load_batch(traj, text)
s.run()
dslist = s.datasetlist
```
Advantages:
* if people prefer to use `cpptraj`'s style
```
parm ./data/tz2.parm7
trajin ./data/tz2.nc
rms @CA
radgyr @CA nomax
```
and dump data directly without writing to file (from `datasetlist`)
*  Speed: all the caluclations were performed at cpptraj's level with zezo python-overhead. And avoid loading traj few times.
* suitable for multiple actions like 'autoimage', 'center'
```
parm ./data/tz2.parm7
trajin ./data/tz2.nc
autoimage
center
rms @CA
radgyr @CA nomax
```
* get benefit from ``pytraj``, such as loading a bunch of files easily
```
traj = pt.iterload('traj.*.nc', …
```
> add load_batch

- pytraj/common_actions.py
- pytraj/pmap.py
- tests/test_pmap.py
```python
data = pt.pmap(4, ['angle :3 :4 :5', 'distance @10 @20'], traj)
```
The output still looks ugly, but I think it does its job.
```python
OrderedDict([('Ang_00002', array([ 69.68716988,  60.2844541 ,  54.42705162, ...,  71.3034791 ,
54.10386015,  65.28664506])), 
('Dis_00003', array([ 3.91279372,  3.90062135,  4.53520013, ...,  6.5440018 ,
5.95743058,  6.91264439]))])
```
> naive support parallel with cpptraj commands

- pytraj/__init__.py
- pytraj/core/ActionList.pyx
- tests/test_ActionList.py
- tests/test_run_docstring.py
```python
In [1]: pt.create_pipeline(traj, ['autoimage', 'rms', 'center'])
Out[1]: <generator at 0x2aaad39e39c8>
```
just like cpptraj's command below but the current (modified) state of Frame is kept. We can freely to play further with this state. It's layz because we don't actually do anything.
```python
parm prmtop
trajin traj.nc
autoimage
rms
center
```
This make user much easier to plug his/her method to cpptraj's stream
```python
def new_method(traj, ...):
for frame in traj:
do_some_thing_fun(frame)
yield frame
fi = pt.create_pipeline(traj, ['autoimage', 'rms', 'center'])
new_method(fi)
> add create_pipeline for lazy computing

- examples/mpi_examples/pmap_mpi_0.py
- pytraj/parallel/__init__.py
- pytraj/parallel/parallel_mapping_mpi.py
- pytraj/parallel/parallel_mapping_multiprocessing.py
* mpi mode
```
pmap_mpi(pt.radgyr, traj) # don't need to provide n_cores here. We use `mpirun -n 4 ...`
```
Ideally, we should only have one `pmap` method but this make the code a bit more complicated. so just make them `pmap` for `multiprocessing` and `pmap_mpi` for `MPI`.
* multiprocessing mode
```
pmap(pt.radgyr, traj, n_cores=4)
```
```python
pmap_mpi(['autoimage', 'center :2', 'distance :3 :7', 'angle :3 :7 :8'], traj)
```
output:
```python
OrderedDict([('Dis_00000', array([  9.48439863,   9.79616302,   9.35450479,   9.57256816,
10.09955627,   9.6236227 ,  10.36017486,  10.04639645,
10.03293064,   9.45615558])), ('Ang_00001', array([ 74.91719744,  69.71458237,  
74.35604139,  78.17689569,
76.70314718,  77.91747126,  75.12749319,  77.83048564,
79.6697457 ,  82.159786  ]))])
```
We …
> consistent API for pmap_mpi

- pytraj/Frame.pxd
- pytraj/Frame.pyx
- pytraj/__version__.py
- tests/test_force.py
related to https://github.com/Amber-MD/cpptraj/pull/147
@ctlee
I just add force to pytraj for Frame too. Currently only work with `iterload`
```python
traj = pt.iterload('systemVF.nc', 'systemVF.parm7')
for f in traj: print(f.force)
In [5]: traj[-1].force
Out[5]:
array([[ -5.84547138,  18.11874962,   7.36161375],
[  5.74563074, -10.81376553,  -7.01832628],
[ -0.60432696,  -6.89329529,  -3.81471229],
...,
[-17.49478149,  29.7173996 , -14.54843998],
[  1.76848102, -26.37628555,  10.8654871 ],
[ 12.65101337,   0.54338849,   3.11959696]])
```
> support force: only work with TrajectoryIterator from iterload for now

- pytraj/parallel/parallel_mapping_multiprocessing.py
- tests/test_pmap.py
make the API is more consistent between pytraj's method and cpptraj's command lines
python method:
```python
In [1]: pt.pmap(pt.radgyr, traj, n_cores=3)
Out[1]: 
OrderedDict([('RoG_00000',
array([ 18.91114428,  18.93654996,  18.84969884,  18.90449256,
18.8568644 ,  18.88917208,  18.9430491 ,  18.88878079,
18.91669565,  18.87069722]))])
```
```python
In [3]: pt.pmap(['radgyr nomax', ], traj, n_cores=3)
Out[3]: 
OrderedDict([('RoG_00000',
array([ 18.91114428,  18.93654996,  18.84969884,  18.90449256,
18.8568644 ,  18.88917208,  18.9430491 ,  18.88878079,
18.91669565,  18.87069722]))])
```
OrderedDict is used if cpptraj return multiple datasets
```python
In [4]: pt.pmap(['radgyr nomax', 'distance :3 :7'], traj, n_cores=3)
Out[4]: 
OrderedDict([('RoG_00000',
array([ 18.91114428,  18.93654996, …
```
> output for pmap should always return OrderedDict: ack, hate this

- pytraj/core/action_list.pyx
- scripts/timing/timing_distance_actionlist.py
pytraj tried to setup Topology for every frame because the boolean flag has never set properly. damn.
Lesson learnt: always try to use `pytraj._verbose(True)` to see what cpptraj is saying.
fixing one line of code speeds up pytraj 12 times. ack.
- add timing script to make sure pytraj can catch up cpptraj's speed too.
> fixing my freaking idiot mistake when processing Topology for ActionList

- .gitignore
- pytraj/core/action_list.pyx
- pytraj/parallel/parallel_mapping_multiprocessing.py
- setup.py
- tests/test_ActionList.py
- tests/test_pmap.py
cpptraj's commands as a single text
```python
data = pt.pmap('''angle :3 :4 :5
distance @10 @20''', traj, n_cores=2)
```
a list of cpptraj command (list of strings)
```python
data = pt.pmap(['angle :3 :4 :5',
'distance @10 @20'], traj, n_cores=2)
```
should produce identical output.
Probably 1st case is good save my time when testing with ipython. But I prefer to have users to use 2nd case.
> add cpptraj text to pmap: not sure if this is a good idea

- pytraj/__init__.py
- pytraj/common_actions.py
- pytraj/datasets/cpp_datasets.pxd
- pytraj/datasets/cpp_datasets.pyx
- tests/test_frame_indices.py
- tests/test_pca.py
- tests/test_projection.py
Try to make pca in pytraj similiar to sklearn too?
current usage
```python
In [20]: pt.pca(traj, '@P', n_vecs=2)
Out[20]: 
(array([[ 10.36236763,  10.03283119,  14.62098026, ..., -10.45174313,
-10.81758785, -12.98321533],
[-11.02234077,  -8.2722187 ,  -6.74612713, ...,  -0.53519076,
-3.8595717 ,  -2.75687122]], dtype=float32),
(array([ 44.79219281,  32.29500218]),
array([[-0.16254271,  0.11974073, -0.21648397, ..., -0.16616231,
0.16027767, -0.09431382],
[ 0.08633618,  0.15009632,  0.04454871, ...,  0.15871903,
0.00325103, -0.16614721]])))
```
Tutorial: http://amber-md.github.io/pytraj/latest/tutorials/tut_pca.html
> simplify pca calculation

- pytraj/all_actions.py
- tests/test_pca.py
https://github.com/Amber-MD/pytraj/issues/1112
```python
traj = pt.load("data/tz2.nc", "data/tz2.parm7")
ref = pt.load('data/tz2.rst7', traj.top)
mask = '!@H='
pt.pca(traj, mask, n_vecs=2, ref=ref)
```
is equal to
```bash
parm data/tz2.parm7
reference data/tz2.rst7
trajin data/tz2.nc
rms reference !@H=
matrix covar name MyMatrix !@H=
createcrd CRD1
run
runanalysis diagmatrix MyMatrix vecs 2 name MyEvecs
crdaction CRD1 projection evecs MyEvecs !@H= out project.dat beg 1 end 2
```
> add reference to pca

- pytraj/parallel/multiprocessing_.py
- tests/test_pmap.py
aim: make the syntax consistent between serial and parallel runs.
```python
pt.rmsd(traj, mask, ref=3)
pt.pmap(pt.rmsd, traj, mask=mask, ref=3, n_cores=4)
```
> add option to use int value for ref in parallel

- setup.py
amber tag: 09b058c8c5db9f1bb65cbef6beea6e104fb69772
@swails: thanks for the fix. Per clang/conda/osx/pytraj stuff, I am only able to get it done for standalone cpptraj version: by manually changing "CXX=clang++" to "CXX=clang++ -stdlib=libstdc++". I don't know how to change this in amber yet. :D
> add Jason fix for osx

- pytraj/all_actions.py
try to add `calc_` to most of actions to make the syntax consistent. But now I don't like this way.
hide it from website doc.
Another reason to add `calc_` keyword before since there are some commands that give different output formats from cpptraj's ones.
> make doc nicer

- pytraj/c_traj/c_trajectory.pxd
- pytraj/c_traj/c_trajectory.pyx
- pytraj/trajectory_iterator.py
- tests/test_superpose.py
- tests/test_template_for_doc.py
This method is mainly for NGLView in Jupyter notebook, to view out-of-core data.
It's good to do translation and rotation on the fly.
```python
import pytraj as pt
import  nglview as nv
traj = pt.iterload('big_traj.nc', 'big_top.parm7')
traj.superpose(ref=0, mask='@CA')
view = nv.show_pytraj(traj)
```
> lazy superpose

- pytraj/c_traj/c_trajectory.pyx
- tests/test_actionlist_trajectoryiterator.py
issue
```python
traj = pt.iterload(...)
traj.autoimage()
traj[:1] # autoimage is not updated.
```
this PR fix that.
Related: https://github.com/arose/nglview/pull/168
> fix slicing when using lazy transformation

- pytraj/all_actions.py
- pytraj/datasets/c_datasets.pyx
- pytraj/get_common_objects.py
- run_tests.py
- tests/test_actionlist.py
- tests/test_superpose.py
The source of error is that cpptraj's DataSet_Coords does not do checking n_atoms (topology vs frame) when adding new Frame.
`pytraj` force Frame must have the same n_atoms as Topology.
```python
def add_frame(self, Frame frame):
if self.top.n_atoms != frame.n_atoms:
raise ValueError("Frame and Topology must have the same number of atoms")
self.baseptr_1.AddFrame(frame.thisptr[0])
```
> fix alignment/rmsd when using reference with different atom number

- examples/example_cpptraj_style.py
- pytraj/c_action/actionlist.pxd
- pytraj/c_action/actionlist.pyx
uhm, this makes customizing a group of commands easier
```python
def compute_method(traj, ...):
cm = """
"""
return pytraj.compute(cm, traj, *args, **kwd)
```
ack. I should think about this earlier.
> example: using cpptraj style + add `PrintActions` for ActionList

- pytraj/io.py
- tests/test_write_data.py
only support 1D array for now. Still having this #1280 issue.
```python
rmsd_data = pt.rmsd(traj, ref=0)
pt.io.write_data('my.agr', rmsd_data)
```
> ADD support write_data (xmgrace, gnu, ...)

- pytraj/analysis/energy_analysis.py
- tests/energies/test_sander_energies.py
try Niel's files:
```python
import sander
import pytraj as pt
import parmed as pmd
inp = sander.pme_input()
parm_file = 'prmtop'
rst7_file = 'inpcrd'
parm = pmd.load_file(parm_file, rst7_file)
with sander.setup(parm_file, parm.coordinates, parm.box, mm_options=inp):
e, f = sander.energy_forces()
print('from pysander: ',e.elec)
traj = pt.iterload(rst7_file, parm_file)
ene = pt.esander(traj, mm_options=sander.pme_input())
print('from pytraj: ', ene['elec'][0])
```
output
```bash
from pysander:  -8225.698560432662
from pytraj:  -8225.69856043
```
> ensure pytraj reproduce elec energy

- pytraj/all_actions.py
- pytraj/builder/build.py
- pytraj/trajectory/trajectory_iterator.py
- pytraj/utils/check_and_assert.py
- scripts/base_setup.py
- tests/test_make_structure.py
```bash
pt.make_structure(traj, command='ref:1-13:1-13', ref=ref)
```
Excluding reference name since we explicitly passing the `ref`
> change makestructure reference syntax

- tests/test_analysis/test_center_of_mass.py
- tests/test_analysis/test_check_chirality.py
- tests/test_analysis/test_closest.py
- tests/test_analysis/test_dihedral_analysis.py
- tests/test_analysis/test_distance.py
- tests/utils.py
This fixes some tests where the input file names were using absolute paths instead of the `fn()` function from `utils.py`. Also adds a function `outputname()` to `utils.py` to fix output file paths, which fixes `test_closest.py`.
> Fix some tests (correct path)

- scripts/base_setup.py
For unknown reasons (that I don't want to go deeper), this failed after switching to git submodule.
Only affect if making AmberTools tarfile.
https://travis-ci.org/Amber-MD/ambertools-ci/jobs/231353763
```bash
fatal: Not a git repository: ../../../.git/modules/AmberTools/src/pytraj
Traceback (most recent call last):
File "setup.py", line 100, in <module>
write_version_py()
File "/home/travis/build/Amber-MD/ambertools-ci/amber16/AmberTools/src/pytraj/scripts/base_setup.py", line 120, in write_version_py
FULLVERSION, GIT_REVISION = get_version_info()
File "/home/travis/build/Amber-MD/ambertools-ci/amber16/AmberTools/src/pytraj/scripts/base_setup.py", line 88, in get_version_info
GIT_REVISION = git_version()
File "/home/travis/build/Amber-MD/ambertools-ci/amber16/AmberTools/src/pytraj/scripts …
```
> fix git version writing

- pytraj/analysis/hbond_analysis.py
- tests/test_analysis/test_hbond.py
private for now since I don't know how to nicely display the data yet.
```python
traj = pt.iterload(fn('tz2.ortho.nc'), fn('tz2.ortho.parm7'))
hb = pt.hbond(
traj, ':10,11', solvent_donor=':WAT', solvent_acceptor=':WAT')
assert hb._get_bridge() ==  \
[[('WAT208', 'THR10', 'TRP11')],
[('WAT208', 'THR10', 'TRP11')],
[('WAT208', 'THR10', 'TRP11')],
[('WAT208', 'THR10', 'TRP11')],
[],
[],
[],
[],
[],
[('WAT266', 'THR10', 'TRP11')]]
```
> ADD: hbond _get_bridge for solvent bridge

- pytraj/trajectory/c_traj/c_trajectory.pyx
- tests/test_analysis/test_velocity.py
- tests/test_trajectory/test_fancy_indexing.py
- Code example
```python
def test_velocity(self):
traj = pt.iterload(
fn('issue807/trunc.nc'), fn("issue807/system.prmtop"))
aa_eq(pt.get_velocity(traj),
pt.get_velocity(traj[:]))
aa_eq(pt.get_velocity(traj, frame_indices=[1, 3, 5]),
pt.get_velocity(traj[[1, 3, 5]]))
```
- Also (gradually) adapt pytest style
> ENH: slice on-dist trajectory with velocity will give a on-mem trajectory with velocity

- CMakeLists.txt
- scripts/base_setup.py
The CMake build system requires some changes to pytraj.  In CMake, the location of compiled files is decided by CMake, and is not guaranteed to be consistent.   So, you can't just use the Amber lib directory.  You *almost* had the right setup for CMake to pass in the locations via `CPPTRAJ_LIBDIR` and `CPPTRAJ_HEADERDIR`; I just had to edit `base_setup.py` so that it will use those variables when they are provided even if pytraj is being built inside Amber.
Also, I designed the CMake build system to not modify the source directory at all so as to make using Git easier, and I found the `build -b <dir>` argument to Distutils to relocate the Python built files.  However, there doesn't seem to be any way to tell Cython not to put its generated files in the source directory, at least from the …
> Add CMake build system changes

- CMakeLists.txt
- devtools/ci/setup_env.sh
- scripts/base_setup.py
It turns out I missed something when I manually merged my changes to base_setup.py.  I still need to add a block that will use the environment compilers if AMBERHOME is not defined.
> Add one more thing for CMake build system

- CMakeLists.txt
With this change, you can build OpenMP Amber on Macs without getting errors from pytraj.  
This should fix the Jenkins CI build.
> CMake: disable openmp build on Macs

- CMakeLists.txt
Now, CMake will set pytraj's LDFLAGS to add in the correct RPATH for finding the Amber libraries on OS X.  I decided to make this change in CMake, not in setup.py, so as to not risk breaking pytraj's standalone build, and the Amber Makefile build.
This also adds a minor fix for pytraj OpenMP sometimes being built before `libcpptraj_omp` in Amber.
This fixes Amber-MD/cmake-buildscripts#70 and Amber-MD/cmake-buildscripts#66
> CMake: set RPATH properly on OS X, fix pytraj OpenMP being built out of order

- pytraj/trajectory/c_traj/c_trajectory.pyx
- tests/test_analysis/test_pca.py
The pca() function will degenerate the input TrajectoryIterator because of an inappropriate re-initiation of  actionlist. 
Also added a test to the test_pca.py to make sure the fix works.
> solve pca() degenerates input TrajectoryIterator issue

- Jenkinsfile
This can be configured to pull any version of libcpptraj to build
against so that we can test with an arbitrary cpptraj pull request.
> Quick test with libcpptraj docker image

- pytraj/core/c_core.pxd
- pytraj/core/c_core.pyx
This should fix the breakage caused by https://github.com/Amber-MD/cpptraj/pull/777
Should be considered WORK IN PROGRESS until that PR is accepted.
> WIP: The ReplaceAsterisk() function has been deprecated.

- pytraj/core/topology_objects.pyx
- tests/test_topology_objects/test_topology_objects.py
Fix #1531
I changed the dtype of arr from int to i4 and added a test.
> Fixed problem with bonded_indices() method of pytraj.Atom class

- pytraj/io.py
- pytraj/topology/topology.pyx
When the to_parmed method of the pytraj.topology.topology.Topology class is invoked, the
I got the following error.
```
File "pytraj/topology/topology.pyx", line 874, in pytraj.topology.topology.Topology.to_parmed
File "pytraj/topology/topology.pyx", line 875, in pytraj.topology.topology.Topology.to_parmed
File "pytraj/topology/topology.pyx", line 837, in pytraj.topology.topology.Topology.save
TypeError: save() got an unexpected keyword argument 'overwrite'
```
python: 3.8.1
cpptraj: V4.26.2 (GitHub)
pytraj: 2.0.5.dev0
ParmEd: 3.2.0
The reason for this error is that Topology.save does not have an argument 'overwrite'.
So, I added 'overwrite' to the argument of ParmFile.write as well as Topology.save.
Of course, we can also remove overwrite=True from Topology.to_parmed (line 875 of …
> WIP: remove runtime error in pytraj.topology.topology.Topology.to_parmed. 

- tests/test_external_loading/test_parmed_converter.py
Add a test for pytraj.topology.topology.to_parmed in relation to #1533.
In an environment where ParmEd 3.2.0 is installed, the newly added test succeeded.
```
test_external_loading/test_parmed_converter.py::TestParmEdConverter::test_parmed_converter PASSED
```
> ADD a test for pytraj.topology.topology.Topology.to_parmed

- pytraj/parallel/dataset.py
- pytraj/utils/get_common_objects.py
- pytraj/utils/tools.py
When running the test, warnings about numpy occur, such as the following.
So, I have modified it so that there is no warning for the future.
```
pytraj/pytraj/parallel/dataset.py:39: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
mat = np.sum((val[0] * val[1]
pytraj/pytraj/parallel/dataset.py:46: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
mat = np.sum((val[0][1] * val[1]
pytraj/pytraj/parallel/dataset.py:48: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence …
```
> remove warnings about numpy

- pytraj/core/parameter_types.pyx
- tests/test_topology.py
When I called angle_indices of the pytraj.topology.topology.Topology,
I got the following error.
```
File "pytraj/topology/topology.pyx", line 751, in pytraj.topology.topology.Topology.angle_indices.__get__
File "/home/uchida/cnt/enhancer/utils/.venv/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
I added a `return` statement at the end of `indeces` in pytraj.core.parameter_types.AtomType and also added a test.
> Fixed problem with angle_indices of pytraj.topology.topology.Topology

- pytraj/topology/topology.pyx
- pytraj/trajectory/stripped_trajectory.py
- scripts/memory/topology_test.py
https://github.com/Amber-MD/pytraj/issues/1495
Below code should run without increasing memory
```python
import pytraj as pt
orig_top = pt.load_topology('../../tests/data/tz2.parm7')
def test():
for i in range(100000000):
print(i)
top = orig_top.copy()
top.strip(":1")
test()
```
> FIX memory leak in stripping

- pytraj/topology/topology.pyx
The instances created by `bonds`, `angles` and `dihedrals` of `topology.topology.Topology` are always updated with each call.
So, I propose to redeclare a new instance at the time of the call.
> FIX: Redeclaration of the instance in Topology.bonds

- pytraj/trajectory/c_traj/c_trajectory.pyx
When iterating over a sliced trajectory which contains forces, the forces were not included in the new sliced trajectory, this fixes that.
Before:
```
>>> import pytraj as pt
>>> traj = pt.iterload('03_Prod.nc','parm7')
>>> traj[0:5][0].force
>>>
```
After:
```
>>> import pytraj as pt
>>> traj = pt.iterload('03_Prod.nc','parm7')
>>> traj[0:5][0].force
array([[ -3.07928634,   0.68935108,  -0.12736608],
[  7.64932537, -19.16348267, -16.6106205 ],
[ -2.71725702,  -1.42881477,   8.08388519],
...,
[  9.62166405,  -1.84283781,  -4.25340939],
[  0.85549378,   5.10778189, -12.62469864],
[ -8.67284012,   3.77264452,   8.0937624 ]])
```
> Fix disappearing forces when slicing

- tests/test_analysis/test_jcoupling.py
This is a workaround, pointing the Jcoupling test to the new location of the Karplus.txt file in cpptraj. @hainm I initially tried to create a new variable called cpptraj_dat_dir in testing.py (code below), but I kept getting an ImportError. This should work for now.
```python
__all__ = [
'load_sample_data', 'eq', 'aa_eq', 'duplicate_traj', 'Timer', 'tempfolder',
'amberhome', 'cpptraj_test_dir', 'cpptraj_dat_dir', 'get_fn', 'get_remd_fn',
'assert_equal_topology'
]
```
`<snip>`
```python
if cpptrajhome:
cpptraj_test_dir = os.path.join(cpptrajhome, 'test')
cpptraj_dat_dir = os.path.join(cpptrajhome, 'dat')
else:
if amberhome:
cpptraj_test_dir = os.path.join(amberhome, 'AmberTools', 'src',
'cpptraj', 'test')
cpptraj_dat_dir = os.path.join(amberhome, 'dat')
else:
cpptrajhome = ''
amberhome = …
```
> Fix Jcoupling test

- pytraj/__init__.py
- pytraj/core/c_options.pyx
- tests/test_analysis/test_randomize_ions.py
- tests/test_analysis/test_velocity.py
Related to cpptraj [PR 882](https://github.com/Amber-MD/cpptraj/pull/882), adds ability for pytraj to set what RNG will be used. This will make it so tests can pass if the default RNG is changed. 
@hainm sorry this is pretty rough code, you may want to make it a nicer interface eventually (like taking strings or enum instead of `int` ).
> Add ability to set RNG in tests

- tests/test_analysis/test_cluster.py
Hopefully this will future-proof the test case in case cluster ends up generating more sets. 
@hainm It would be better long-term to be able to select by DataSet name/aspect.
> Use positive index instead of negative to select data set in cluster test case

- pytraj/topology/topology.pyx
Had a little look at the memory leak bug Amber-MD/pytraj#1615 as it was also annoying me.
Needed to delete the newParm pointer created by cpptraj after assignment as it remained on the heap. Not sure if this is the best way to handle it but it fixes the memory leak.
> Fix memory leak on topology mask selection

- CMakeLists.txt
Pytraj was being built differently than other python programs in AmberTools, which was causing the build to fail on certain platforms. This PR adds the proper flags to be passed to `setup.py` in `CMakeLists.txt`.
Amber Gitlab reference: https://gitlab.ambermd.org/amber/amber/-/merge_requests/1238
> Import python build fix for AmberTools cmake.

- pytraj/analysis/nucleic_acid_analysis.py
Skip nxyz for now (since self._summary is not that important).
> Update nucleic_acid_analysis.py: skip nxyz for now 

- .github/workflows/python-package-conda.yml
- pytraj/utils/tools.py
- tests/test_analysis/test_rmsd.py
- tests/test_io/test_convert.py
Certain numpy deprecation warnings seem to be errors depending on the platform. In particular, this was causing a lot of spurious test failures on Jenkins. This PR attempts to fix the 3 most commonly failing tests on Jenkins:
```
=========================== short test summary info ============================
FAILED test_read_to_array.py::Test::test_0 - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (11,) + inhomogeneous part.
FAILED test_analysis/test_rmsd.py::TestSimpleRMSD::test_list_of_masks - ValueError: don't mix different types
FAILED test_io/test_convert.py::Test::test_0 - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 …
```
> Try to fix some test warnings that can be errors on certain platforms.

- .github/workflows/python-package-conda.yml
- environment.yml
- pytraj/parallel/dataset.py
- pytraj/trajectory/c_traj/c_trajectory.pyx
Try to fix some test errors that seem to show up with python 3.11. @hainm please especially check the change in `c_trajectory.pyx1. I'm not completely certain of the intent behind the original code, but changing it to something like `if not idxs` did not fix the error.
> Fix python 3.11 test issues

- pytraj/__init__.py
- pytraj/all_actions.py
- tests/test_analysis/test_count_in_voxel.py
This analysis command is meant to be used with GIST analysis to estimate water residence time for a given region. 
When running GIST on a trajectory, we get a list of voxels and their associated rotational/translational entropy of solvent atoms. We can focus on low-entropy voxels (which behave differently from the bulk) and find the population of solvent atoms in a voxel throughout the course of a simulation to measure how long it's taking for solvent molecules to equilibrate in and out of solvent pockets on the macromolecular interface (survival time correlation function).
> Implemented "count in voxel" function

- pytraj/all_actions.py
- tests/test_analysis/test_rdf.py
Hello everyone, 
I just updated the rdf action with an optional boolean argument `raw_rdf`.
When `raw_rdf` is set to True, the returned rdf values are not normalized, as the `rawrdf` argument in cpptraj.
> rdf action should be able to return the raw-rdf values
