- setup.py
Since released code is freezed now, it's time to update pytraj version
in master branch.
> PYTRAJ: update delopment version

- note-books/multidihedral_analysis.ipynb
update: multidihedral_analysis.ipynb
> PYTRAJ: example with pandas' DataFrame

- installs/install_cpptraj_git.sh
- setup.py
or not having CPPTRAJHOME.
install with -j4
> PYTRAJ: add install cpptraj from github if not having AMBERHOME

- note-books/speed_test.ipynb
> PYTRAJ: speed: pytraj vs mdtraj

- examples/mpi_calc_molsurf_0.py
I though I would get segmentation fault for reading TrajReadOnly
in parallel. But there is nothing bad happens. will check later.
> PYTRAJ example comment: update

- pytraj/externals/_load_ParmEd.py
form here: https://github.com/ParmEd/ParmEd/issues/117#issuecomment-96871159
> PYTRAJ: add "indices" for "bonds" in chem

- note-books/speed_test.ipynb
link:
http://nbviewer.ipython.org/github/pytraj/pytraj/blob/master/note-books/speed_test.ipynb
> PYTRAJ: update speed test for iterating and indexing

- note-books/speed_test.ipynb
speed is different from time to time since mdtraj use openmp and
I did not set specific number of cores. (defaul=use whatever cores available)
> PYTRAJ  notebook: clarify the speed comparison

- note-books/speed_test.ipynb
Just update speed test for loading and iterating Trajectory.
pytraj is generally is few times faster.
If I used FrameArray (in memory traj) to iterate frame, pytraj will be
3000 times faster :D (of course we can not compare apple with orange)
> PYTRAJ: speed test

- note-books/speed_test.ipynb
%timeit for frame in traj(10, 999, 10): pass # twice faster
%timeit for frame in u.trajectory[10:999:10]: pass
> PYTRAJ: speed_test - add frame iterator for a chunk

- README.md
> PYTRAJ: add Amber14 manual to README.md

- note-books/Trajectory.ipynb
user should expect gettting TrajReadOnly when calling 'io.load'
> PYTRAJ: update notebook for Trajectory.ipynb

- README.md
> PYTRAJ: update README.md: flexiblity in reading file extension

- pytraj/api.py
I am idiot when doing this:
for arr0 in self.xyz (make a copy of 3D array, ack)
should be
for i in range(self.xyz.shape[0]):
frame = Frame()
frame.append_xyz(self.xyz[i])
yield frame
> PYTRAJ: update api.Trajectory for faster iterating: 200 times

- devtools/unused_pyx_pxd_files/api_memview/_api.pyx
- devtools/unused_pyx_pxd_files/api_memview/api.py
even using Cython does not make the iteration faster.
Move the test files into unused_pyx_pxd_files to remind myself not to try later
> PYTRAJ: add trial speed upgrade for api.pyx

- note-books/speed_test.ipynb
quite slow (although still a bit faster than other pk). I need to
work on this.
> PYTRAJ: update speed test for iterload

- note-books/index.ipynb
link: (hope this work)
http://nbviewer.ipython.org/github/pytraj/pytraj/tree/master/note-books/index.ipynb
> PYTRAJ: add index.ipynb

- note-books/saving_data_or_traj.ipynb
link:
http://nbviewer.ipython.org/github/pytraj/pytraj/blob/master/note-books/saving_data_or_traj.ipynb
> PYTRAJ: add saving_data_or_traj notebook

- note-books/FAQ.ipynb
- note-books/index.ipynb
this is actually for myself and other `pytraj` developer.
Link:
http://nbviewer.ipython.org/github/pytraj/pytraj/blob/master/note-books/FAQ.ipynb
> PYTRAJ: update FAQ notebook.

- pytraj/Topology.cpp
- pytraj/Topology.pyx
- pytraj/externals/_load_mdtraj.py
- tests/test_autoimage.py
Just need to add Box info into pytraj's Frame object
From this issue:
https://github.com/mdtraj/mdtraj/issues/814
> PYTRAJ: autoimage: support this action when loading traj from `mdtraj`

- .travis.yml
don't know why travis failed. nvm.
> PYTRAJ: turnoff install mdtraj from github

- README.md
make no sense to use mine status
> PYTRAJ: change build status badge from hainm/pytraj to pytraj/pytraj

- examples/mpi_examples/mpi_calc_molsurf_0_list_of_trajs.py
- examples/mpi_examples/mpi_calc_molsurf_0_single_traj.py
- note-books/index.ipynb
- note-books/parallel/mpi_calc_molsurf.ipynb
- pytraj/parallel/map.py
- tests/test_Topology_3.py
add decorator to check "chemistry"
> PYTRAJ: minor

- examples/mpi_examples/mpi_calc_molsurf_0_list_of_trajs.py
- examples/mpi_examples/mpi_calc_molsurf_0_single_traj.py
- note-books/parallel/mpi_calc_molsurf.ipynb
- pytraj/parallel/map.py
user just need:
total_arr = pymap(comm, pyca.calc_molsurf, traj, "@CA", top=traj.top, root=0)
if comm.rank == 0:
Link:
http://nbviewer.ipython.org/github/pytraj/pytraj/blob/master/note-books/parallel/mpi_calc_molsurf.ipynb
> PYTRAJ: much more simple parallel "map" method.

- pytraj/core/Box.cpp
- pytraj/core/Box.pyx
- tests/test_Box.py
we can quickly assign new Box for Frame like
>>> frame.box = [35.2627796623, 41.8455476799, 36.168629529, 90.0, 90.0, 90.0]
This is equal to
>>> box = Box(array('d', [35.2627796623, 41.8455476799, 36.168629529, 90.0, 90.0, 90.0])
>>> frame.box = box
> PYTRAJ: enhance creating Box

- pytraj/Topology.cpp
- pytraj/Topology.pyx
- tests/test_Topology_box.py
just as simple as:
>>> topology.box = [100, 200, 300, 90, 90, 90]
> PYTRAJ: update set box for Topology

- note-books/dev/speed_test_distance.ipynb
to my opinion: it's not worth trying implmenting openmp in pytraj. might
be due to my limited knowledge about it.
MPI is more interesting since it's very easy to implment in `pytraj` +
we can easily split trajectories to get good scaling.
> PYTRAJ: ah, add our openmp version for calc_distance too

- pytraj/datasets/DataSet.cpp
- pytraj/datasets/DataSet.pyx
there will be diffent format: cpptraj, json, pickle
> PYTRAJ: add `save` method for DataSet

- README.md
> PYTRAJ: add `Contributors and Acknowledgement` in README.md

- pytraj/io.py
- tests/test_load_from_frame_iter.py
> traj = io.iterload("./data/md1_prod.Tc5b.x", "./data/Tc5b.top")
> # strip atoms
> new_top = traj.top.strip_atoms("!@CA", copy=True)
> fa = mdio.load(traj(0, 5, mask='@CA'), top=new_top)
> PYTRAJ: add _load_from_frame_iter for memory saving

- tests/test_FrameArray_load_universal.py
traj = Trajectory(mdtraj_object, top) # where `top` is our pytraj's
Topology
> PYTRAJ: test load mdtraj objecct with our given Topology

- devtools/for_travis/setup_env.sh
> PYTRAJ: need to pip install psutil to make memory_profiler happy

- pytraj/DataSetList.cpp
- pytraj/DataSetList.pyx
- pytraj/Trajectory.cpp
- pytraj/Trajectory.pyx
- pytraj/datasets/DataSet.cpp
- pytraj/datasets/DataSet.pyx
- tests/test_Trajectory_insert.py
- tests/test_dataset_math.py
- tests/test_load_MDAnalysis.py
- tests/test_memory_assert_0.py
Aim: mimic a part of Pandas.
(we can install pandas but seems overkill + recent pandas update just
broke my Python3 version). My aim is to make pytraj less depend on other
packages.
> PYTRAJ: some math to DataSet

- tests/test_frame_iter_speed.py
- tests/test_traj_math.py
(always)
or using
for idx, frame in enumerate(traj):
do_something_good_with(frame)
> PYTRAJ: add spped test to show that we should use: for frame in traj

- pytraj/DataSetList.pyx
See if this still prevents the segfault -- it will avoid the leak described in #408
> Try an alternative.

- pytraj/_auto_funcs.py
- pytraj/misc.py
add auto-generated funcs (start with "calc" for my quick testing
and quick check cpptraj manual.
normally, I use
from pytraj import info
info("grid")
but now
from pytraj import _auto_funcs as a
info(a.calc_grid) # save time since ipython has autocomplete
> PYTRAJ: add _auto_funcs and update misc.

- note-books/parallel/parallel_with_ipython.ipynb
- pytraj/TrajectoryIterator.py
- pytraj/parallel/__init__.py
- pytraj/tools.py
ipython is reall really great.
> pytraj: parallel_with_ipython

- devtools/travis-ci/setup_env.sh
- pytraj/externals/_load_ParmEd.py
- pytraj/io.py
- tests/test_load_from_url.py
- tests/test_run_docstring.py
* `pytraj.load_topology`
* `pytraj.load`
> load from url (through parmed)

- pytraj/array.py
- setup.py
- tests/test_run_docstring.py
https://github.com/Amber-MD/pytraj/issues/749
> fix '--help' option of setup.py prints successful install message

- .travis.yml
- runtests.py
- setup.py
update ./runtest.py -verbose for python2
> runtests.py

- installs/install_cpptraj_current_folder.sh
- installs/install_cpptraj_git.sh
- pytraj/core/ActionList.pyx
- tests/test_ActionList.py
endless streaming
```python
traj = pt.iterload("./data/md1_prod.Tc5b.x", "./data/Tc5b.top")
commands = ['rmsd @CA',
'distance :3 :7',
'distance     :3 :7',
'vector :2 :3']
dslist = CpptrajDatasetList()
actlist = ActionList(commands, traj.top, dslist=dslist)
for frame in traj:
actlist.do_actions(frame)
```
> enhance ActionList

- pytraj/cluster/__init__.py
- tests/test_ActionList.py
closely related to this: https://github.com/Amber-MD/cpptraj/issues/35#issuecomment-149593671
> add refindex

- pytraj/trajectory.py
- tests/test_trajs/test_Trajectory.py
> add syntax sugar for merging two trajs

- pytraj/core/brick.pxd
- pytraj/core/brick.pyx
- pytraj/topology.pxd
- pytraj/topology.pyx
- tests/fun.py
- tests/test_topology/test_Topology.py
relate to https://github.com/Amber-MD/cpptraj/issues/133
> mutate atom

- pytraj/_nastruct.py
- tests/test_nastruct.py
related to 
- https://github.com/Amber-MD/cpptraj/issues/121
- https://github.com/Amber-MD/cpptraj/pull/152
> add assert for major and minor groove, match 3dna, cool cpptraj

- pytraj/testing.py
- tests/test_NH_order_parameters.py
- tests/test_ired_TODO.py
relate to https://github.com/Amber-MD/pytraj/issues/985
> use absolute dir for looking for cpptraj test files

- pytraj/__init__.py
- pytraj/common_actions.py
- pytraj/io.py
- tests/test_pmap.py
- tests/test_volmap.py
- enhance volmap
- reduce n_cores for pmap testing to make travis happy
- autoconvert xyz to c contiguous if xyz is not C order memory block.
> volmap, pmap, c contiguous

- pytraj/__init__.py
- pytraj/common_actions.py
- pytraj/hbond_analysis.py
- pytraj/nucleic_acid_analysis.py
- tests/issues/test_issue991_buffer_not_C_contiguous.py
- tests/test_angle.py
- tests/test_center_of_mass.py
- tests/test_dihedral.py
- tests/test_hbond.py
- tests/test_iterators/test_frame_iter_mutable_vs_unmutable.py
- tests/test_iterators/test_frame_iter_with_autoimage.py
- tests/test_iterators/test_iter_not_same_frame.py
- tests/test_load/test_load_indices.py
- tests/test_merge_coordinates.py
- tests/test_merge_coordinates_frames.py
- tests/test_timecorr.py
- extend hbond doc, argument
- add more file ext tests, related to https://github.com/Amber-MD/cpptraj/issues/161
> hbond, update test

- pytraj/__init__.py
- pytraj/actions/CpptrajActions.pxd
- pytraj/actions/CpptrajActions.pyx
- pytraj/core/action_list.pyx
- tests/test_do.py
- tests/test_unstrip.py
add `pytraj.do` too
```python
pt.do(['autoimage', 'radgyr nomax @CA', 'rms refindex 0', 'rms refindex 1'], 
traj, ref=[ref0, ref1]))
vs.
pt.create_pipeline(traj, ['autoimage', 'rms']) --> return Frame iterator for lazy evaluation
pt.do: eager evaluate the data
```
> add Action_Unstrip

- pytraj/__init__.py
- pytraj/_shared_methods.py
- pytraj/core/action_list.pyx
- pytraj/frameiter.py
- pytraj/io.py
- pytraj/trajectory.py
- pytraj/trajectory_iterator.py
- pytraj/utils/check_and_assert.py
- tests/test_ActionList.py
- tests/test_do.py
- pytraj.do accept a callable function too
> change FrameIter to FrameIterator

- pytraj/_get_common_objects.py
- pytraj/common_actions.py
- pytraj/io.py
- scripts/base_setup.py
- setup.py
- tests/test_docs.py
- add python setup.py clean to remove temp files to avoid side effect
> enhance get_coordinates + clean for setup

- pytraj/common_actions.py
- tests/test_frame_indices.py
still turn off a test. related to this issue in cpptraj: https://github.com/Amber-MD/cpptraj/issues/172
waiting for feedback.
> frame_indices for atomiccorr

- pytraj/common_actions.py
- pytraj/core/brick.pxd
- pytraj/core/brick.pyx
- pytraj/frame.pyx
- pytraj/tools.py
- pytraj/topology.pyx
- tests/test_docs.py
- tests/test_frame_indices.py
- tests/test_pickle.py
- tests/test_topology.py
So just create a lightweight topology.
> add Simplified topoloy objects (Atom, Res, Topology) for fast iterating

- pytraj/actions/CpptrajActions.pyx
- pytraj/common_actions.py
- pytraj/core/action_list.pyx
- pytraj/cyutils.pyx
- pytraj/dihedral_analysis.py
- pytraj/dssp_analysis.py
- pytraj/hbond_analysis.py
- pytraj/io.py
- pytraj/nucleic_acid_analysis.py
- pytraj/topology.pyx
- pytraj/trajectory.py
- tests/test_iterators/test_iterframe_master.py
thanks @drroe for the tip (which makes pytraj 30% faster when iterating Trajectory)
> only set_mass once

- pytraj/common_actions.py
- tests/test_atomiccorr.py
- tests/test_mean_structure.py
related to https://github.com/Amber-MD/cpptraj/pull/176
> more test for atomiccorr

- pytraj/cluster/__init__.py
- pytraj/common_actions.py
- pytraj/core/action_list.pyx
- pytraj/utils/progress.py
- tests/.coveragerc
related to https://github.com/Amber-MD/cpptraj/pull/182
> turn off cluster info in cpptraj for pytraj + progress bar

- pytraj/__init__.py
- pytraj/actions/CpptrajActions.pyx
- pytraj/common_actions.py
- tests/energies/test_pmap_sander.py
- tests/test_frame_indices.py
- tests/test_randomize_ions.py
also make the syntax is more Pythonic (good for auto-completion).
> write test for randomize ion

- .travis.yml
- devtools/travis-ci/after_success.sh
- pytraj/common_actions.py
only has report for py2, got problem with unicode stuff with py3.
[report sample] (https://coveralls.io/builds/4337313/source?filename=%2Fhome%2Ftravis%2Fminiconda%2Fenvs%2Fmyenv%2Flib%2Fpython2.7%2Fsite-packages%2Fpytraj%2Fmatrix.py)
> add coverage report on coveralls.io

- pytraj/__init__.py
- scripts/ambertools_git/git_diff_amber_git_pytraj_github.sh
> bring view module to main namespace

- pytraj/all_actions.py
- pytraj/parallel/__init__.py
- pytraj/parallel/multiprocessing_.py
- pytraj/shared_methods.py
- pytraj/trajectory_iterator.py
- tests/test_pmap.py
- tests/test_worker_state.py
implement #1092 
Example
```python
def change_10_atoms(traj):
for frame in traj:
frame.xyz[:10] += 1.
yield frame
traj = pt.iterload("data/tz2.nc", "data/tz2.parm7")
data_parallel = pt.pmap(pt.radgyr, traj, n_cores=2, apply=change_10_atoms)
fi = change_10_atoms(traj)
data = pt.radgyr(fi, top=traj.top)
```
> insert a function to pmap if needed

- setup.py
add from @rmcgibbo's suggestion https://github.com/Amber-MD/cpptraj/pull/222
> add -Wl,--no-undefined

- pytraj/all_actions.py
- pytraj/c_action/actionlist.pyx
- pytraj/c_action/c_action.pyx
- pytraj/frameiter.py
- pytraj/hbond_.py
- pytraj/nmr.py
- pytraj/nucleic_acid_.py
- pytraj/vector.py
- tests/test_actionlist.py
- tests/test_iterators/test_chunk_iter.py
- tests/test_iterators/test_frame_iter_3.py
- tests/test_rmsd.py
- tests/test_unstrip.py
- tests/test_vector_analysis.py
> rename do_action to compute; process_topology to check_topology

- pytraj/all_actions.py
- pytraj/c_action/actionlist.pyx
- pytraj/get_common_objects.py
- pytraj/nmr.py
- pytraj/vector.py
- tests/test_actionlist.py
- tests/test_io.py
- tests/test_pmap.py
- tests/test_rmsd.py
- tests/test_vector_analysis.py
```python
actlist = pt.ActionList()
actlist.add(...)
```
> rename add_action to add

- .travis.yml
- pytraj/all_actions.py
- pytraj/c_action/actionlist.pxd
- pytraj/c_action/actionlist.pyx
- pytraj/c_action/c_action.pxd
- pytraj/c_action/c_action.pyx
- pytraj/hbond_.py
- tests/test_actionlist.py
https://github.com/Amber-MD/cpptraj/pull/228
small change for ActionFrame
> follow cpptraj update about MPI

- pytraj/parallel/mpi.py
- tests/test_mpi/test_mpi_reference.py
```python
pt.pmap_mpi(pt.rmsd, traj, ref=3)
```
> update reference for mpi

- pytraj/all_actions.py
- tests/test_rmsd.py
related to https://github.com/Amber-MD/cpptraj/pull/245
> add nomod for rmsd

- pytraj/all_actions.py
- tests/test_rmsd.py
https://github.com/Amber-MD/pytraj/pull/1138#discussion_r52063214
also add a test for the combination of those 3.
> fix RMD options = ' '.join((nofit_ + mass_, nomod_))

- .travis.yml
- devtools/travis-ci/coveralls
- devtools/travis-ci/install_cpptraj.sh
- devtools/travis-ci/run_tests.sh
- devtools/travis-ci/setup_env.sh
- examples/mpi_examples/run_mpi_examples.sh
- scripts/install_libcpptraj.py
- tests/test_docs.py
- tests/test_mpi/test_mpi.py
- tests/test_mpi/test_mpi_cpptraj_style.py
- tests/test_mpi/test_mpi_load_batch.py
- tests/test_mpi/test_mpi_reference.py
- tests/test_order_parameters.py
- tests/test_pmap.py
- tests/test_run_mpi.py
add `CXX="g++ -stdlib=libstdc++"` to force cpptraj to use libstdc++ if gnu is used.
> add CXX flag for cpptraj: osx trick

- devtools/travis-ci/setup_env.sh
related to: https://github.com/Amber-MD/conda-recipes/pull/6
> temporary use of pysander from hainm channel so we can test on osx

- pytraj/all_actions.py
- pytraj/datasets/c_datasets.pyx
- tests/test_rotdif.py
but wait for https://github.com/Amber-MD/cpptraj/issues/93
> update rotdif a bit

- pytraj/all_actions.py
- pytraj/c_traj/c_trajectory.pyx
- tests/test_pca.py
- tests/test_transform_trajectory_iterator.py
still not efficient but it's ok for now.
> ADD: pca for out-of-core trajectory too.

- pytraj/__init__.py
- pytraj/all_actions.py
- tests/test_wavelet.py
example: 
```python
traj = pt.load("data/DPDP.nc", "data/DPDP.parm7")
traj.superpose('@C,CA,N', ref=0)
command = 'name mywave nb 10 s0 2 ds 0.25 type morlet \
correction 1.01 chival 0.25 :1-22 cluster minpoints 66 epsilon 10.0'
data = pt.wavelet(traj, command)
```
> ADD: Minimal support for wavelet

- setup.py
issue https://github.com/Amber-MD/pytraj/issues/1238
(thanks to Matthew Zwier, @mczwier)
> fix detection openm in libcpptraj

- pytraj/all_actions.py
- pytraj/c_action/actionlist.pxd
- pytraj/c_action/actionlist.pyx
- pytraj/c_action/c_action.pyx
- pytraj/c_traj/c_trajectory.pyx
- pytraj/frameiter.py
- pytraj/hbond_analysis.py
- tests/test_actionlist.py
- tests/test_iterators/test_chunk_iter.py
- tests/test_iterators/test_frame_iter_3.py
- tests/test_pca.py
- tests/test_rmsd.py
- tests/test_transform_trajectory_iterator.py
phew, finally I know my mistake.
Basically, when calling `traj_on_disk.autoimage().superpose()` pytraj will create ActionList object 
and perform `autoimage` for first frame. However, when calling `autoimage`, ActionList would be already setup, it does not accept any further Action. So just trick ActionList to tell it to resetup.
> correct setup for ActionList to make traj_on_disk.autoimage().superpose() works correctly

- pytraj/__init__.py
- pytraj/all_actions.py
- pytraj/c_action/c_action.pxd
- pytraj/c_action/c_action.pyx
- pytraj/c_traj/c_trajectory.pyx
- pytraj/trajectory.py
- pytraj/trajectory_iterator.py
- scripts/memory/superpose_traj_on_disk.py
- tests/test_superpose.py
- tests/test_transform_trajectory_iterator.py
follow: https://github.com/Amber-MD/cpptraj/pull/335
> ADD (update) align action

- pytraj/shared_trajectory.py
- pytraj/trajectory.py
- pytraj/trajectory_iterator.py
- pytraj/visualization/nglview_wrapper.py
```python
view = traj.view()
view.add_pytraj_trajectory(traj2)
```
> add nglview wrapper for pytraj

- README.md
- examples/pytraj_readme.ipynb
> gif for pytraj

- run_tests.py
- scripts/base_setup.py
- scripts/cythonize.py
- scripts/find_lib.py
- setup.py
> change exit(0) to exit(1)

- examples/example_water_clustering.py
- pytraj/__init__.py
- pytraj/all_actions.py
- pytraj/c_action/actionlist.pyx
- pytraj/cluster/__init__.py
- pytraj/datasetlist.py
- pytraj/datasets/c_datasetlist.pyx
- pytraj/get_common_objects.py
- pytraj/trajectory.py
- setup.py
- tests/test_actionlist.py
- tests/test_center.py
- tests/test_cluster.py
- tests/test_cpptraj_dataset.py
also add minimal support for `dbscan`, `hieragglo`, `dpeaks`. add test cases too.
https://github.com/Amber-MD/cpptraj/pull/346
> update clustering - Follow cpptraj pr 346

- licenses/externals/jupyter-themes.txt
- pytraj/utils/css/oceans16.css
- pytraj/utils/theme.py
> add oceans16 theme for notebook

- .travis.yml
- pytraj/__init__.py
- pytraj/all_actions.py
- pytraj/c_traj/c_trajectory.pyx
- tests/test_density.py
- tests/test_image.py
- also turn off osx on travis (for now. I am not sure why get segmentation fault again).
> support density + image command

- pytraj/all_actions.py
- pytraj/datasets/c_datasets.pxd
- pytraj/datasets/c_datasets.pyx
- tests/test_density.py
related to https://github.com/Amber-MD/cpptraj/issues/383
> Density: x|y|z value

- pytraj/io.py
- tests/test_write_data.py
a simple method that use `CpptrajState` for converting data format
```python
pt.io._format_convert('my.dx', 'my.ccp4')
```
> adding _format_convert

- pytraj/datafiles/__init__.py
- tests/test_write_data.py
```python
pt.datafiles.convert('my.ccp4', 'my.dx')
```
> convert file

- scripts/base_setup.py
- setup.py
> Fix type error2

- scripts/install_libcpptraj.py
avoid complicated install. related to #1297
> use -nosanderlib

- .travis.yml
- MANIFEST.in
- devtools/travis-ci/install_pytraj.sh
- devtools/travis-ci/run_tests.sh
- devtools/travis-ci/test_setup_command.py
- scripts/base_setup.py
- setup.py
`python setup.py ...` and `pip install ...`
> add test for setup command line

- pytraj/analysis/dssp_analysis.py
amber commit: dec1b7fe4fd7d78ad20014d0213386fd55bb88ed
> correction from Scott

- pytraj/topology/topology.pyx
- tests/test_topology_objects.py
... so I can use the nested 
`atom.residues.atoms`
> some works on SimplifiedTopology

- pytraj/utils/progress.py
- tests/test_progress_bar.py
fix some file open without closing issue.
> not require tqdm for normal users

- pytraj/parallel/base.py
- pytraj/parallel/multiprocess.py
- tests/test_pmap.py
> make hbond work with pmap

- pytraj/parallel/base.py
- tests/test_pmap.py
> ensure data from hbond (pmap) will be int type

- pytraj/__init__.py
- pytraj/all_actions.py
- pytraj/parallel/base.py
- pytraj/trajectory/frameiter.py
- pytraj/utils/__init__.py
- pytraj/utils/tools.py
- tests/template_unittest.py
- tests/test_check_chirality.py
- tests/test_check_structure.py
- tests/test_checkoverlap.py
- tests/test_drmsd.py
- tests/test_extra_coverage.py
- tests/test_iterators/test_iter_not_same_frame.py
- tests/test_iterators/test_iterframe_indices.py
- tests/test_mindist.py
- tests/test_principal_dorotation.py
- tests/test_rotdif.py
- add `do_action` method to avoid duplicated codes
```python
c_dslist, stdout = do_action(traj, command, Action_Radgyr)
```
- add `check_chirality`
- turn on `rotdif`
> refactor code

- .travis.yml
- devtools/travis-ci/install_pytraj.sh
- pytraj/analysis/rmsd.py
- scripts/install_libcpptraj.py
- scripts/misc/fix_rpath_pip_osx.py
- tests/test_analysis/test_volmap.py
try to  be smart (?) about netcdf stuff by using `'@rpath/libnetcdf.7.dylib'`
> netcdf osx

- tests/test_tranformation/test_autoimage.py
#https://github.com/Amber-MD/cpptraj/pull/431
> test_autoimage_for_tightly_packed_systems

- pytraj/__init__.py
- pytraj/analysis/c_action/__init__.py
- pytraj/analysis/topology_analysis.py
- tests/test_analysis/test_topology_analysis.py
follow https://github.com/Amber-MD/cpptraj/pull/435
still getting trouble with capturing c++ stdout.
> Topology Info stuff (angleinfo, topologyinfo, ...)

- pytraj/core/c_options.pyx
- pytraj/topology/topology.pyx
- tests/test_pickle.py
Very minor - just corrected the spelling of "suppress".
> Fix function name recently changed in cpptraj

- pytraj/analysis/c_action/c_action.pxd
- pytraj/analysis/c_action/c_action.pyx
- pytraj/analysis/hbond_analysis.py
- tests/test_analysis/test_velocity.py
- tests/test_docs.py
Action_Hbond has been renamed Action_HydrogenBond; related to Amber-MD/cpptraj#485.
> Fix 'hbond' command

- changes.rst
- pytraj/__init__.py
- pytraj/all_actions.py
- pytraj/testing/testing.py
- tests/test_analysis/test_ti.py
https://github.com/Amber-MD/cpptraj/pull/495
> WIP: naive support for TI

- pytraj/core/topology_objects.pyx
- pytraj/topology/topology.pxd
- pytraj/topology/topology.pyx
- tests/test_topology.py
- nested objects
```python
atom.residue.name
atom.residue.atoms
```
- add bond_partners
```python
atom.bond_partners
```
EXPERIMENTAL
> Try to mimic ParmEd API for SimplifiedTopology

- pytraj/__init__.py
- pytraj/all_actions.py
- pytraj/analysis/c_action/c_action.pxd
- pytraj/analysis/c_action/c_action.pyx
- run_tests.py
- scripts/libcpptraj_tools/write_action_pyx.py
- tests/test_analysis/test_fiximagedbonds.py
https://github.com/Amber-MD/cpptraj/pull/504
> SUPPORT: fiximagedbonds

- pytraj/analysis/hbond_analysis.py
- pytraj/parallel/base.py
- setup.py
- tests/test_parallel_pmap/test_pmap.py
> hbond pmap with bridge

- pytraj/__init__.py
- pytraj/all_actions.py
- scripts/libcpptraj_tools/find_missing_cpptraj_action_names.py
- tests/test_analysis/test_velocity.py
```python
pt.set_velocity(traj, temperature=298, ig=10)
```
#1393
> Set velocity

- .travis.yml
- conda-requirements.txt
- devtools/ci/setup_env.sh
- pip-requirements.txt
- scripts/base_setup.py
- scripts/install_libcpptraj.py
- setup.py
> Try not to use bleeding edge versions.

- pytraj/all_actions.py
- tests/test_analysis/test_velocity.py
https://github.com/Amber-MD/cpptraj/pull/563
> velocityautocorr: usevelocity -> usecoords

- .travis.yml
- devtools/ci/test_setup_command.py
https://github.com/Amber-MD/cpptraj/pull/566
> fix test (follow https://github.com/Amber-MD/cpptraj/pull/566)

- pytraj/all_actions.py
- tests/test_analysis/test_volmap.py
#1438
and delete outdated tests.
> Fix volmap

- circle.yml
- devtools/ci/setup_env.sh
- devtools/circle-ci/setup_env.sh
- scripts/install_libcpptraj.py
- tests/test_analysis/test_rmsd.py
https://github.com/Amber-MD/cpptraj/issues/585#issuecomment-374198887
> add --requires-flink

- pytraj/all_actions.py
- tests/test_analysis/test_nativecontacts.py
- tests/test_io/test_io.py
fix #1466 
Also fix test failure in test_io.py
> FIX distance in native contacts

- .gitignore
- pytraj/analysis/rmsd.py
> added notes to rmsd doc

- .travis.yml
- scripts/install_libcpptraj.py
- setup.py
Seems work fine with
```
export MACOSX_DEPLOYMENT_TARGET=10.14
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```
> remove stdlibc++

- pytraj/io.py
- pytraj/trajectory/c_traj/c_trajectory.pyx
- pytraj/utils/cyutils.pyx
- tests/test_io/test_io.py
- tests/test_iterator/test_iterframe_indices.py
```
traj = pt.load(fn, top=tn, frame_indices=[-1])
```
close #1465
> accept negative indices

- .travis.yml
- pytraj/all_actions.py
- setup.py
Copied from ParmEd
https://github.com/ParmEd/ParmEd/blob/8ea11835cacbb986d76439f56bb529c83d34aa1f/setup.py#L28
> dealing with mac versions

- pytraj/datasets/c_datasets.pxd
- pytraj/datasets/c_datasets.pyx
- pytraj/datasets/cast_dataset.pyx
- pytraj/datasets/datasetlist.py
> update to follow cpptraj change (Use DataSet_integer_mem)

- pytraj/trajectory/c_traj/c_trajectory.pyx
- tests/test_io/test_io.py
> FIX getting segmentation fault if loading a trajectory with force but not velocity

- pytraj/cluster/__init__.py
- tests/test_analysis/test_cluster.py
- tests/test_io/test_io.py
> FIX cluster analysis: make sure to write datafiles

- Jenkinsfile
to keep the pytraj jobs from sitting in a zombie state on Jenkins
> Implement a timeout 

- setup.py
> Document setup, install and test requirements

- pytraj/io.py
- tests/test_io/test_io.py
- Start using python 3 syntax: Path and f-string.
- Mock
> code clean (boring stuff)

- pytraj/all_actions.py
- pytraj/analysis/c_action/c_action.pxd
- pytraj/analysis/c_action/c_action.pyx
- pytraj/core/topology_objects.pyx
- pytraj/testing/testing.py
- pytraj/topology/topology.pxd
- pytraj/topology/topology.pyx
- pytraj/utils/tools.py
- tests/test_analysis/test_angle.py
- tests/test_do.py
- tests/test_pickle.py
- tests/test_pipeline.py
- tests/test_trajectory/test_transform_trajectory_iterator.py
Changes needed for pytraj to work after https://github.com/Amber-MD/cpptraj/pull/845 is merged. 
@hainm can you double check that all looks ok? Once I get the green light from you I can merge cpptraj 845 and then this can be merged,
I note there is this in the test output:
```
test_trajectory/test_trajectory_writer.py::test_trajectory_writer_open_close Internal Error: TrajoutList::AddTrajout() called with empty filename.
Error: Could not determine trajectory '/tmp/tmpxad332b8/test.x' format.
Error: Could not set up trajectory '/tmp/tmpxad332b8/test.x'
PASSED
```
However, this seems to be present in master as well so I don't think it's related to this PR.
> Update pytraj for new cpptraj molecule handling

- pytraj/analysis/c_action/actionlist.pyx
- tests/test_actionlist.py
> issue-1553: pt.compute does not raise error when there is a error

- pytraj/analysis/nucleic_acid_analysis.py
https://github.com/Amber-MD/cpptraj/issues/851#issuecomment-710747944
> nastruct: add post_process

- tests/test_analysis/test_randomize_ions.py
Algorithm was recently improved in cpptraj PR 887: https://github.com/Amber-MD/cpptraj/pull/887
This PR just changes the test seed and the target save file.
> Fix randomizeions test

- pytraj/trajectory/c_traj/c_trajectory.pyx
- tests/test_trajectory/test_trajectory.py
- tests/test_trajectory/test_trajectory_extensive_indexing.py
- tests/test_trajectory/test_trajectory_writer.py
https://github.com/Amber-MD/pytraj/issues/1579
> Fix negative index for trajectory with 1 frame

- pytraj/__init__.py
- pytraj/all_actions.py
- tests/test_analysis/test_closest_atom.py
Pushing code for a simple function that finds the closest_atom to a given xyz coordinate tuple.
I want to extend this to finding all atoms in a given radius centered at xyz coordinate, check if atom x is in a voxel that has cube with center xyz and dimensions n, specifically for providing ready-made functions used in GIST analysis.
> added closest_atoms function to all_actions.py and wrote test code (WIP)

- pytraj/all_actions.py
- AnalysisRunner: simplifies analysis functions by handling dataset creation and analysis execution.
> AnalysisRunner
